services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ragchat-postgres
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: ragchat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag -d ragchat"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ragchat-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    # Healthcheck disabled - curl not available in qdrant image
    # For production, use Qdrant Cloud with built-in health monitoring
    # Or install curl via custom Dockerfile
    healthcheck:
      disable: true

volumes:
  pgdata: {}
  qdrant_data: {}
